import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const nunito = Nunito({
  subsets: ["latin"],
  variable: '--font-nunito'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body className="bg-primary-color">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
