import 'bootstrap/dist/css/bootstrap.css'
import { Inter, Roboto } from "next/font/google";
export const metadata = {
  title: 'My Next.js',
  description: 'Shop generated by Next.js',
  aplicationName : 'Next.js',
  keyboard: ['Next.js', 'React', 'Javascript'],
  author : [
    {name: 'Jonathan Javier Urquiza'}, 
    {email:'jurquiza86@hotmail.com'},
    {https:'//nextjs.org'}
  ],
  publisher: 'Jonathan Javier Urquiza',
  creator: 'Jonathan Javier Urquiza'
}
const roboto = Roboto({
  weight: ['300', '400', '500'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
})
const inter = Inter ({
  weight: ['300', '400'],
  style: [ 'normal'],
  subsets: ['greek']
})


export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
